openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: https://localhost:8888/v1
paths:
  /cache/{key}:
    get:
      operationId: GetCache
      parameters:
        - name: key
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
  /admin/cache/{key}:
    post:
      operationId: PostCache
      parameters:
        - name: key
          in: path
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          "application/json":
            schema:
              type: object
      responses:
        '200':
          description: OK